package BufferApp;


/**
* BufferApp/Buffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* dimanche 3 mars 2024 17 h 53 CET
*/

public interface Buffer extends BufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Buffer
